[package]
name = "fs-web"
version = "0.1.0"
authors = ["ice_iix <ice_ix@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
